name: ocm.software/plugin-registry
version: ((REGISTRY_VERSION))
provider:
  name: ocm.software
labels:
  - name: category
    value: plugin-registry
  - name: registry
    value: official
  - name: description
    value: Official OCM plugin registry
references:
  - name: helminput
    version: ((HELMINPUT_VERSION))
    component: ocm.software/plugins/helminput
    digest:
      hashAlgorithm: ((HELMINPUT_DIGEST_ALGO))
      normalisationAlgorithm: ((HELMINPUT_DIGEST_NORM))
      value: ((HELMINPUT_DIGEST_VALUE))
